#!/usr/bin/env bash
# Git utility command to show contents of blob from subfoldered hash
# Usage: git unhash .git/objects/11/<rest-of-SHA1-hash>

HASH=(${1//\// })

if [ ${#HASH[@]} -ne 1 ]; then
	HASH=${HASH[${#HASH[@]} - 2]}${HASH[${#HASH[@]} - 1]}
fi

git show $HASH
