#!/usr/bin/env bash

cd _posts
DATE=`date +%Y-%m-%d`

if [ "$#" -eq 0 ]; then
	FILENAME=$DATE-new-post.md
elif [ "$#" -eq 1 ]; then
	POSTNAME=$1
	NAME=${POSTNAME// /-}
	LOWERCASE="$(echo $NAME | tr '[A-Z]' '[a-z]')"
	FINAL="$(echo ${LOWERCASE//[._,\'!?#:]/})"
	FILENAME=$DATE-$FINAL.md
else 
	echo "Illegal number of parameters"
	exit
fi

touch $FILENAME

echo '---' >> $FILENAME
echo 'layout: post' >> $FILENAME

if [ "$#" -eq 0 ]; then
	echo 'title:  "New Post"' >> $FILENAME
else
	echo "title:  \"$1\"" >> $FILENAME
fi

echo 'comments: True' >> $FILENAME
echo '---' >> $FILENAME
vi $FILENAME
